### ISSUE TITLE
Make sure all example projects have description in the POM

### ISSUE THREAD

**Issue by jhrcek** [kiegroup/kie-wb-playground#9]
The description of the project (pom.xml > project > description) is used to render description in the new library perspective UI (see screenshot). Please make sure that all projects in this repo have suitable description.

Currently some projects don't have any description (evaluation) while others have relatively uninformative description (e.g. Optacloud: "This workbench example assigns processes to computers." could be improved "This workbench example illustrates usage of optaplanner to solve optimization problem of assigning processes to computers")

![screenshot from 2017-02-17 12-26-36](https://cloud.githubusercontent.com/assets/2716069/23063858/0b2c5164-f50d-11e6-8afa-f21b97efa743.png)

**Comment by ge0ffrey** [comment]
None of the other repo's have an issues tab, as we standarize on jira, so I am removing the issues tab here.
Issues should go in: https://issues.jboss.org/projects/PLANNER (DROOLS, JBPM, etc)

Regardless, thanks for reporting this issue. It looks like JBPM-5767 already duplicates this one, so closing this one is fine.
